name: Tweet each release
on:
  push:
    tags:
      - v*
jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
      - uses: ethomson/send-tweet-action@v1
        with:
          status: "Watch out aeternity new release for ${{ github.repository}}\n"
          consumer-key: ${{ secrets.API_KEY }}
          consumer-secret: ${{ secrets.API_KEY_SECRET }}
          access-token: ${{ secrets.ACCESS_TOKEN }}
          access-token-secret: ${{ secrets.ACCESS_TOKEN_SECRET }}
          
